kpm fixes the order of dependencies and format in kcl.mod and kcl.mod.lock
kcl-lang/kpm pull request #336
Opened 2024-05-24 18:54 UTC by officialasishkumar

#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [ ] N
- [x] Y #333  

#### 2. What is the scope of this PR (e.g. component or file name):

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Other

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [ ] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [ ] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [ ] Manual test (add detailed scripts or steps below)
- [ ] Other

2024-05-28 02:40 UTC, officialasishkumar commented
I will do the required changes.

2024-05-28 12:45 UTC, d4v1d03 commented on pkg/package/modfile.go
> +func (deps *Dependencies) SortMapByKey() {
Hey @Peefy , i've done some changes at #334, please have a look over them if they are in the right direction.

2024-05-29 02:39 UTC, zong-zhe requested changes

2024-06-03 07:37 UTC, officialasishkumar commented
@Peefy  The migration is not yet completed.

2024-06-28 03:36 UTC, zong-zhe commented
Hi @officialasishkumar 😄

This PR conflicts with the main branch. Are you still working on it？

2024-06-28 04:10 UTC, officialasishkumar commented
> Hi @officialasishkumar 😄
>
> This PR conflicts with the main branch. Are you still working on it？

Yeah, I will complete it. Sorry my exams were running for a few weeks. Now it's over.

2024-07-04 07:40 UTC, zong-zhe commented
Hi @officialasishkumar 😄

I finished this issue for the 0.9.0 release, https://github.com/kcl-lang/kpm/pull/373
You'll be able to focus on the LFX now.

2024-07-04 07:41 UTC, closed without merging